## Day 2 – Pandas Basics
Dataset: HR Employee Attrition
Goal: Import, explore, update, delete, index and sort data.

In [3]:
import pandas as pd

## Import dataset into a Pandas DataFrame

In [4]:
df = pd.read_excel("/content/HR-Employee-Attrition.xlsx")

In [5]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [6]:
df.shape

(1470, 35)

## Explore columns

In [7]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

## Explore Series

In [8]:
print(df["Age"].head())

0    41
1    49
2    37
3    33
4    27
Name: Age, dtype: int64

## Add a new column

In [9]:
df["IncomePerYear"] = df["MonthlyIncome"] * 12

In [10]:
print(df[["MonthlyIncome", "IncomePerYear"]].head())

   MonthlyIncome  IncomePerYear
0           5993          71916
1           5130          61560
2           2090          25080
3           2909          34908
4           3468          41616

## Update a column

In [11]:
df["IncomePerYear"] = df["MonthlyIncome"] * 12

In [12]:
print(df["IncomePerYear"].head())

0    71916
1    61560
2    25080
3    34908
4    41616
Name: IncomePerYear, dtype: int64

## Delete a column

In [13]:
df["TemporaryColumn"] = "Practice"

## Delete rows using index

In [14]:
df_without_first_row = df.drop(index=0)

In [15]:
print("\nRows after deleting index 0:", df_without_first_row.shape[0])

Rows after deleting index 0: 1469

## Set custom index

In [16]:
indexed_df = df.set_index("EmployeeNumber")

In [20]:
indexed_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,IncomePerYear,TemporaryColumn
EmployeeNumber,,,,,,,,,,,,,,,,,,,,,
1,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,0,8,0,1,6,4,0,5,71916,Practice
2,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,3,...,1,10,3,3,10,7,1,7,61560,Practice
4,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,0,7,3,3,0,0,0,0,25080,Practice
5,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,4,...,0,8,3,3,8,7,3,0,34908,Practice
7,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,1,...,1,6,3,3,2,2,2,2,41616,Practice

## Sort by MonthlyIncome

In [18]:
sorted_df = df.sort_values(by="MonthlyIncome", ascending=False)

In [19]:
print(sorted_df[["EmployeeNumber", "Age", "JobRole", "MonthlyIncome"]].head(10))

      EmployeeNumber  Age            JobRole  MonthlyIncome
190              259   52            Manager          19999
746             1035   41  Research Director          19973
851             1191   56            Manager          19943
165              226   50            Manager          19926
568              787   55            Manager          19859
918             1282   51            Manager          19847
749             1038   52            Manager          19845
1242            1740   40            Manager          19833
898             1255   43  Research Director          19740
956             1338   56            Manager          19717